config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'
  devise_for :users

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments
  mount_uploader :image, ImageUploader

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments

  # 自分がフォローしているユーザーを集める
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # 自分をフォローしているユーザーを集める
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(tweet_id: params[:tweet_id], body: params[:comment][:body])
    comment.save
    redirect_to tweet_path(params[:tweet_id])
  end

  def destroy
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweets_path
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @tweet = Tweet.new
  end

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    @comment = Comment.new
    @comments = Comment.where(tweet_id: params[:id])
  end

  def create
    @tweet = Tweet.new(tweet_params)  # フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
    @tweet.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
    @tweet.save
    redirect_to tweets_path
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    redirect_to tweet_path(@tweet.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
    redirect_to tweets_path
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body, :image) # tweetモデルのカラムのみを許可
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top bg-info">
      <div class="container text-center">
        <ul class="row list-group list-group-horizontal list-unstyled border-white">
          <% if user_signed_in? %>  <!-- deviseのメソッドで、「ログインしているかしていないかでtrue or falseを返す」メソッド -->
            <li class="col-4 col-md p-2"><%= link_to "新規投稿", new_tweet_path, class: "text-white" %></li>
            <li class="col-4 col-md p-2"><%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "text-white" %></li>
            <li class="col-4 col-md p-2"><%= link_to "マイページ", user_path(current_user.id), class: "text-white" %></li>
          <% else %>
            <li class="col-4 col-md p-2"><%= link_to "新規登録", new_user_registration_path, class: "text-white" %></li>
            <li class="col-4 col-md p-2"><%= link_to "ログイン", new_user_session_path, class: "text-white" %></li>
          <% end %>
          <li class="col-4 col-md p-2"><%= link_to "ツイート一覧", tweets_path, class: "text-white" %></li>
          <li class="col-4 col-md p-2"><%= link_to "ユーザー一覧", users_path, class: "text-white" %></li>
        </ul>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

<div class="row my-3 py-3 border-top">
  <%= form_for @tweet, html: {class: "col-12"} do |f| %>
  <p class="row px-3">
    <%= f.label :body,"ツイート", class: "col-10 col-md-2" %>
    <%= f.text_field :body, class: "col-10 col-md-auto" %>
  </p>
  <p class="row px-3">
    <%= f.file_field :image, class: "col-12" %>
  </p>
  <%= f.submit "ツイート更新", class: "btn btn-success btn-sm" %>
  <% end %>
  <p class="col-12 p-3"><span><%= link_to "戻る", tweet_path(@tweet.id), class: "btn btn-primary btn-sm" %></span></p>
</div>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>

<div class="row">
  <% @tweets.each do |tweet| %>
  <article class="card p-1 my-1 col-12">
    <div class="card-body row">
      <h4 class="card-title col-12 col-md-9"><span>email: </span><%= link_to tweet.user.email, user_path(tweet.user.id) %></h4>
      <% if user_signed_in? && current_user != tweet.user %>
      <div class="col-12 col-md-3">
        <% if tweet.user.followed_by?(current_user) %>
        <p class="text-right my-auto"><%= link_to "フォロー済み", user_relationships_path(tweet.user.id), method: :delete, class: "btn btn-outline-primary" %></p>
        <% else %>
        <p class="text-right my-auto"><%= link_to "フォローする", user_relationships_path(tweet.user.id), method: :post, class: "btn btn-primary" %></p>
        <% end %>
      </div>
      <% end %>
      <p class="card-text col-12 mb-4 border-top border-secondary mt-2 pt-2"><span>ツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id), class: "lead" %></p>
      <div class="col-12">
        <div class="row h-100">
          <p class="col-5 my-auto">
            <% if user_signed_in? %>
            <% if tweet.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
            <%= link_to "お気に入り解除: #{tweet.favorites.count}", tweet_favorites_path(tweet.id), method: :delete, class: "btn btn-outline-info" %>
            <% else %>
            <%= link_to "お気に入り登録: #{tweet.favorites.count}", tweet_favorites_path(tweet.id), method: :post, class: "btn btn-info" %>
            <% end %>
            <% else %>
            <span class="btn btn-outline-dark disabled">お気に入り数: <%= tweet.favorites.count %></span>
            <% end %>
          </p>
          <p class="col-7 text-right mt-auto mb-0"><span class="align-bottom">(<%= tweet.created_at %>)</span></p>
        </div>
      </div>
    </div>
  </article>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

<div class="row my-3 py-3 border-top">
  <%= form_for @tweet, html: {class: "col-12"} do |f| %>
  <p class="row px-3">
    <%= f.label :body,"ツイート", class: "col-10 col-md-2" %>
    <%= f.text_field :body, class: "col-10 col-md-auto" %>
  </p>
  <%= f.submit "ツイートする", class: "btn btn-success btn-sm" %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<p><span>email: </span><%= @user.email %></p>
<p><span>ツイート内容: </span><%= @tweet.body %></p>
<% if @tweet.image? %>
<p><%= image_tag @tweet.image.url %></p>
<% end %>

<% if current_user != @user %>
  <% if @user.followed_by?(current_user) %>
    <p><%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></p>
    <% else %>
    <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
  <% end %>
<% else %>
  <p><%= link_to "EDIT", edit_tweet_path(@tweet.id) %></p>
  <p><%= link_to "x", tweet_path(@tweet.id), method: :delete %></p>
<% end %>

<hr>
<p><span>コメント一覧: </span></p>
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.body %> (<%= comment.created_at %>)</li>
  <% end %>
</ul>
<% if user_signed_in? %>
  <%= form_for([@tweet, @comment]) do |f| %>
    <p>
      <%= f.label :body, "コメント" %>
      <%= f.text_field :body %>
    </p>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/followers.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
    <% else %>
      <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
  <% end %>
<% end %>

app/views/users/follows.html.erb
<h1>Users#follows</h1>
<p>Find me in app/views/users/follows.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
    <% else %>
      <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%=link_to user.email, user_path(user.id) %></p>

  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p><%= link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
      <% else %>
      <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
  <% end %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<hr>
<p><span>email: </span><%= @user.email %></p>

<p><%= link_to "フォロー", follows_user_path(@user.id) %></p>
<p><%= link_to "フォロワー", followers_user_path(@user.id) %></p>
<% if current_user != @user %>
  <% if @user.followed_by?(current_user) %>
    <p><%= link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></p>
    <% else %>
    <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
  <% end %>
<% end %>

<% @tweets.each do |tweet| %>
  <hr>
  <p><span>ツイート内容: </span><%=link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>
<% @favorite_tweets.each do |tweet| %>
  <hr>
  <p><span>ファボツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>